# Generated by Django 3.1.2 on 2020-12-22 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_unique_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='date_posted',
        ),
        migrations.AlterField(
            model_name='post',
            name='unique_id',
            field=models.CharField(editable=False, max_length=100, null=True),
        ),
    ]
