# Generated by Django 3.1.2 on 2020-12-28 08:54

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20201223_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(help_text='Fotoğraflarınızı Yükleyiniz', null=True, upload_to=blog.models.upload_to, verbose_name='Fotoğraflar'),
        ),
    ]
