# Generated by Django 3.1.2 on 2020-12-30 09:34

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20201228_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content_city',
            field=models.CharField(max_length=100, null=True, verbose_name='Gidilen Şehir'),
        ),
        migrations.AddField(
            model_name='post',
            name='content_country',
            field=models.CharField(max_length=100, null=True, verbose_name='Gidilen Ülke'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='default/default-photo.jpg', help_text='Kapak Fotoğrafı Yükleyiniz', null=True, upload_to=blog.models.upload_to, verbose_name='Fotoğraflar'),
        ),
    ]
