# Generated by Django 3.1.2 on 2021-01-01 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20201230_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=50, null=True, verbose_name='Hikayenin Başlığı'),
        ),
    ]
