# Generated by Django 3.1.2 on 2020-12-23 10:33

import blog.models
import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_date_posted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
        migrations.AddField(
            model_name='post',
            name='content_cities',
            field=ckeditor.fields.RichTextField(max_length=20000, null=True, verbose_name='Gezdiğim Diğer Şehirler'),
        ),
        migrations.AddField(
            model_name='post',
            name='content_cost',
            field=ckeditor.fields.RichTextField(max_length=20000, null=True, verbose_name='Harcama'),
        ),
        migrations.AddField(
            model_name='post',
            name='content_education',
            field=ckeditor.fields.RichTextField(max_length=20000, null=True, verbose_name='Eğitim ve Okul Hayatı'),
        ),
        migrations.AddField(
            model_name='post',
            name='content_food',
            field=ckeditor.fields.RichTextField(max_length=20000, null=True, verbose_name='Yemekler'),
        ),
        migrations.AddField(
            model_name='post',
            name='content_fun',
            field=ckeditor.fields.RichTextField(max_length=20000, null=True, verbose_name='Eğlence'),
        ),
        migrations.AddField(
            model_name='post',
            name='content_hint',
            field=ckeditor.fields.RichTextField(max_length=20000, null=True, verbose_name='İpuçları'),
        ),
        migrations.AddField(
            model_name='post',
            name='content_transportation',
            field=ckeditor.fields.RichTextField(max_length=20000, null=True, verbose_name='Ulaşım'),
        ),
        migrations.AddField(
            model_name='post',
            name='content_visit',
            field=ckeditor.fields.RichTextField(max_length=20000, null=True, verbose_name='Gezilecek Yerler'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(help_text='Fotoğraflarınızı Yükleyiniz', null=True, upload_to=blog.models.upload_to, verbose_name='Resim'),
        ),
    ]
